### ISSUE TITLE
Gamerule doFireTick false

### ISSUE THREAD

**Issue by FuryOfFools** [JamieBrassel/Lightning-Tweaks#2]
Just why?

**Comment by JamieBrassel** [comment]
It was the cleanest way I could find to prevent fire from spawning at the original lightning strike location. When a LightningBoltEntity is constructed, LightningBoltEntity#igniteBlocks(4) is called. This is literally in the constructor, so I can only catch it in time if I subscribe to the EntityConstructing event. LightningBoltEntity#igniteBlocks(int) has a couple conditions before it actually spawns any fire. It checks that world difficulty is above easy, gamerule doFireTick is true, and that fire can spawn on the blocks. Setting the world difficulty I found to be really difficult to do in a small amount of code and changing whether fire can spawn would require completely overriding FireBlock which would be complicated and potentially bad for compatibility with other mods. Therefore, I decided to set doFireTick to false for less than a tick. By that I mean it sets it to false when the LightningBoltEntity constructor invokes the Entity constructor and sets it back to true when the lightning bolt is added to the world. Since this always occurs within the same tick in Minecraft's code, no game data actually ends up changing due to setting the gamerule. The game doesn't ever check it's value between constructing lightning and spawning it, except when spawning fire in the constructor.
